kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-pvc-stg
  namespace: cache-ns-stg
  labels:
    app: cache-pvc-stg
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
